package com.books.bookreads.model.enums;

public enum Genre {
    ROMANCE, NON_FICTION, FANTASY, SCI_FI, HISTORY, MYSTERY, THRILLER, HORROR, BIOGRAPHY,
    SELF_HELP, PHILOSOPHY, PSYCHOLOGY, ADVENTURE, YOUNG_ADULT, MEMOIR, DYSTOPIAN, DRAMA,
    POETRY, CRIME, GRAPHIC_NOVEL, GOTHIC, NOVEL, FICTION,
}
